sudo: required
language: generic
services:
  - docker
env:
  global:
    - git config --global user.email "jcayouette@suse.com"
    - git config --global user.name "jcayouette"
    - secure: GwQVxM/Jw0mkb/7pdlNbAfEh1zmM2stcdHtP3dw9J0TNHA1xs6aUNHN4XOZjIvs6Gw44lXklBSPtGDKGK+g9ihGOEQzoXI+vGH3S74gW/z8bihiHTCAh5ARIJJLIDHa4FmLyqzN/yN9SkCsMw0ZUs2RMiKk5/9NecuovSn952CCQlWRVYpZFjkoyzaidvtSHYKv95Us8EDESLI6Go1aL2z+mREhF8wXDyMAGRhNAdyW5WooQygGtpGml+BoNGf2OgR1lg8PC28xxMhghNnvqzW6y2Ssou3fxzUYUJbE2MwGxneOo6nEJbna7zt7Pk30QC1zIma7kRFyJVaciOgNezXnW/R6REVkiZx9eSJO5AzKtUxdn7ErPfdoNskNhax3PzWym9ve441hkgJLqD5B+HXnFF3te88lepLlJR5znkuQhI/+cBnq8WUqMRo0QGtazMQJJ3hvs4Rsv7wNxyQhTkrdjry+8sIxt8uEpbzWeHC6BaGt1KbUpfOaS4l36o4x/8xojR3GV3M+GZH2n3uNErNNlvIKZ8Qq+yrvbAVj4662cq61T9d0YxPU74IJtHTvIP2E0zjgRMJMzd2KEMQSlMo9fsets4dllyPg4ttfdFhA+OO+Y10TI+a1/ePKVwyc0sI7rQeHgXdSYpDSzq0gjQGsHuJPZYLBrN4pJO7V8wrY=
before_install:
- git clone https://github.com/uyuni-project/uyuni-docs
- cd uyuni-docs/
- git checkout gh-pages
- rm -rf *
- git clone https://github.com/uyuni-project/uyuni-docs-publisher
- cd uyuni-docs-publisher
- docker pull antora/antora
- docker images
- docker run -u $UID -v `pwd`:/antora --rm -t antora/antora --cache-dir=./.cache/antora uyuni-publisher.yml
- ls -a public/; pwd
- cp -r public/* ../../
- cd ..
- pwd
