name: Build and archive documentation from release branches

on:
  push:
    branches:
      - 'uyuni-20[0-9][0-9].[0-9][0-9]' # Only master will build both Uyuni and SUSE Multi-Linux Manager documentations
      - 'manager-4.3-MU-4.3.[0-9][0-9]?' # Other branches will only build SUSE Manager documentation
      - 'manager-5.0-alpha[0-9]' # Other branches will only build SUSE Multi-Linux Manager documentation
      - 'manager-5.0-beta[0-9]' # Other branches will only build SUSE Multi-Linux Manager documentation
      - 'manager-5.0-rc[0-9]' # Other branches will only build SUSE Multi-Linux Manager documentation
      - 'manager-5.0-gmc[0-9]' # Other branches will only build SUSE Multi-Linux Manager documentation
      - 'manager-5.0-gm' # Other branches will only build SUSE Multi-Linux Manager documentation
      - 'manager-5.0' # Other branches will only build SUSE Multi-Linux Manager documentation
      - 'manager-5.0-MU-5.0.[0-9][0-9]?'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      with:
        path: uyuni-docs

    - name: Checkout uyuni-docs-helper repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      with:
        path: uyuni-docs-helper
        repository: uyuni-project/uyuni-docs-helper

    - name: Configure environment
      run: |
        alias docker='podman'
        mkdir outputs

    - name: Build the Uyuni site documentation
      run: |
        rm -rf ./uyuni # Always clean before building
        cd uyuni-docs-helper
        ./uyuni-docs-helper -r ${{ github.ref_name }} -g https://github.com/${{ github.repository}}.git -o /tmp -c antora-uyuni -p uyuni
        cd ..
        mkdir ./uyuni # Required so the folder name is included later in the archive
        cp -r /tmp/build ./uyuni/uyuni-site
      if: startsWith(github.ref_name, 'uyuni-')

    - name: Archive Uyuni site Documentation
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 #v4.6.1
      with:
        name: documentation-uyuni-site-${{ github.ref_name }}
        path: uyuni/
      if: startsWith(github.ref_name, 'uyuni-')

    - name: Build the Uyuni package documentation
      run: |
        rm -rf ./uyuni # Always clean before building
        cd uyuni-docs-helper
        ./uyuni-docs-helper -r ${{ github.ref_name }} -g https://github.com/${{ github.repository}}.git -o /tmp -c obs-packages-uyuni -p uyuni
        cd ..
        mkdir ./uyuni # Required so the folder name is included later in the archive
        cp -r /tmp/build/packages ./uyuni/uyuni-package
      if: startsWith(github.ref_name, 'uyuni-')

    - name: Archive Uyuni package Documentation
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 #v4.6.1
      with:
        name: documentation-uyuni-package-${{ github.ref_name }}
        path: uyuni/
      if: startsWith(github.ref_name, 'uyuni-')

    - name: Build the SUSE Multi-Linux Manager site documentation
      run: |
        rm -rf ./susemanager # Always clean before building
        cd uyuni-docs-helper
        ./uyuni-docs-helper -r ${{ github.ref_name }} -g https://github.com/${{ github.repository}}.git -o /tmp -c antora-mlm -p mlm
        cd ..
        mkdir ./susemanager # Required so the folder name is included later in the archive
        cp -r /tmp/build ./susemanager/susemanager-site
      if: startsWith(github.ref_name, 'manager-')

    - name: Archive SUSE Multi-Linux Manager site Documentation
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 #v4.6.1
      with:
        name: documentation-suse-multi-linux-manager-site-${{ github.ref_name }}
        path: suse-multi-linux-manager/
      if: startsWith(github.ref_name, 'manager-')

    - name: Build the SUSE Multi-Linux Manager package documentation (only english)
      run: |
        rm -rf ./suse-multi-linux-manager # Always clean before building
        cd uyuni-docs-helper
        ./uyuni-docs-helper -r ${{ github.ref_name }} -g https://github.com/${{ github.repository}}.git -o /tmp -c obs-packages-mlm-en -p mlm
        cd ..
        mkdir ./suse-multi-linux-manager # Required so the folder name is included later in the archive
        cp -r /tmp/build/packages/ ./suse-multi-linux-manager/suse-multi-linux-manager-package
      if: startsWith(github.ref_name, 'manager-')

    - name: Archive SUSE Multi-Linux Manager package Documentation (only english)
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 #v4.6.1
      with:
        name: documentation-suse-multi-linux-manager-package-${{ github.ref_name }}
        path: suse-multi-linux-manager/
      if: startsWith(github.ref_name, 'manager-')

    - name: Archive the changelog
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 #v4.6.1
      with:
        name: changelog
        path: uyuni-docs/CHANGELOG.md
