name: Find unused files
on: push

jobs:
 run:
   name: Find unused files
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repo
     uses: actions/checkout@v2

   - name: Look for unused files
     run: ./find_unused administration client-configuration cookbook installation-and-upgrade quickstart reference retail specialized-guides
