name: Test PDF translations (ja, ko, zh_CN)

on:
  push:
    branches:
      - master  # Only master will build both Uyuni and SUSE Manager documentations
      - manager-4.3 # Other branches will only build SUSE Manager documentation

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      with:
        path: uyuni-docs

    - name: Checkout uyuni-docs-helper repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      with:
        path: uyuni-docs-helper
        repository: uyuni-project/uyuni-docs-helper

    - name: Configure environment
      run: |
        alias docker='podman'
        mkdir outputs

    - name: Build the Uyuni PDFs in Japanese
      run: |
        cd uyuni-docs-helper
        ./uyuni-docs-helper -r ${{ github.ref_name }} -o /tmp -c pdf-all-uyuni-ja -p uyuni
      if: github.ref_name == 'master'

    - name: Build the SUSE Manager PDFs in Japanese
      run: |
        cd uyuni-docs-helper
        ./uyuni-docs-helper -r ${{ github.ref_name }} -o /tmp -c pdf-all-uyuni-ja -p suma

    - name: Build the Uyuni PDFs in Korean
      run: |
        cd uyuni-docs-helper
        ./uyuni-docs-helper -r ${{ github.ref_name }} -o /tmp -c pdf-all-uyuni-ko -p uyuni
      if: github.ref_name == 'master'

    - name: Build the SUSE Manager PDFs in Korean
      run: |
        cd uyuni-docs-helper
        ./uyuni-docs-helper -r ${{ github.ref_name }} -o /tmp -c pdf-all-uyuni-ko -p suma

    - name: Build the Uyuni PDFs in Chinese, Simplified
      run: |
        cd uyuni-docs-helper
        ./uyuni-docs-helper -r ${{ github.ref_name }} -o /tmp -c pdf-all-uyuni-zh_CN -p uyuni
      if: github.ref_name == 'master'

    - name: Build the SUSE Manager PDFs in Chinese, Simplified
      run: |
        cd uyuni-docs-helper
        ./uyuni-docs-helper -r ${{ github.ref_name }} -o /tmp -c pdf-all-uyuni-zh_CN -p suma
