name: UPDATE TRANSLATION FILES
on:
  push:
    branches:
      - manager-4.3.7

jobs:
 run:
   name: Update translation files
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repo
     uses: actions/checkout@v2

   - name: '[TOOLCHAIN] po4a'
     run: |
        wget https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Utils/xUbuntu_20.04/Release.key
        sudo apt-key add Release.key
        sudo add-apt-repository -y -u 'deb https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Utils/xUbuntu_20.04/ ./'
        sudo apt-get install -y po4a

   - name: Update gettext files
     run: |
        make pot

   - name: Commit changes
     uses: EndBug/add-and-commit@v5.3.0
     with:
       author_name: Galaxy CI
       author_email: galaxy-ci@suse.de
       message: 'Automatic commit: update translation files'
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
