name: Linting
on: [push]
jobs:
  prose:
    runs-on: ubuntu-latest

    steps:
    - name: '[CHECKOUT] Checkout branch that triggered this workflow'
      uses: actions/checkout@v2

    - name: 'Set up Ruby 2.6'
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: 'Install Asciidoctor'
      run: gem install asciidoctor

    - name: Vale
      uses: errata-ai/vale-action@v1.4.3
      with:
        # Optional
        styles: |
          https://github.com/errata-ai/Google/releases/latest/download/Google.zip

        # Optional
        config: https://raw.githubusercontent.com/uyuni-project/uyuni-docs/vale-style-checks-prototype/.vale.ini

        files: '["modules/administration", "modules/client-configuration", "modules/installation", "modules/large-deployments", "modules/quickstart-public-cloud", "modules/quickstart-sap", "modules/reference", "modules/retail", "modules/salt", "modules/upgrade"]'

      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


